# Generated by Django 5.1.7 on 2025-03-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["model", "manufacturer"]},
        ),
    ]
